### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by spcornelius**
I know there have been several releases in rapid succession, so sorry about this. Just a bug that was exposed when working on pyodesys.

### CODE REVIEW

**Comment by bjodah** [comment]
No worries, the price one needs to pay for splitting things into multiple repositories :)

Do cv qualifiers really matter in pxd files? I was under the impression that the Cython compiler didn't check const correctness, and in the end it's the actual C/C++ header that ends up being used during compilation.

**Comment by spcornelius** [comment]
I think you are right on that. But whether it was the pxd file or the header, often the cython warppers were failing with a "can't cast X as const X" especially with vectors, ndarray ptrs, and so on. (Even if in pure C++ world we would like atol to be a constant vector within the integration routines)

**Comment by bjodah** [comment]
Gotcha, I am all for keeping cv qualifiers consistent -- was just asking out of curiousity. And yes, I agree that atol should be const there.

**Comment by bjodah** [comment]
This is now tagged & on PyPI as 0.11.4

**Pull request merged**
