### PR TITLE
Add user-supplied jacobian-vector product support to python front-end

### PR DESCRIPTION
**Pull request by spcornelius**
In cases with a large number (100s or more) ODEs, it can be difficult to calculate the full Jacobian, let alone store it (in dense format) in memory. As an alternative, the subset of iterative linear solvers in CVODES/SUNDIALS allow approximation of the action of the full Jacobian via the Jacobian-vector product, which requires only O(N) space and can be calculated by a user-supplied function. 

These changes add this functionality to the Python front-end. Specifically, they allow the user to (optionally) supply a callback calculating the Jacobian-vector product and passing it on to CVODES for use with an iterative linear solver.

### CODE REVIEW

**Comment by bjodah** [comment]
I like the idea of exposing jac_times_vec for use from Python.
Generally I haven't used void * user_data in the signature of the methods (since the user
will be subclassing and has access to *thisptr). Same goes for *tmp pointer: the user can allocate buffers in the constructor of their subclass. (I'm trying to keep the classes in AnyODE agnostic of the solver).

If you need to modify any of the files in AnyODE, would you mind opening a separate pull-request over at https://github.com/bjodah/anyode ? (I should add that as a proper submodule in this repo--feel free to do se)

Will you open another PR? (I notice that you've closed this one)

**Comment by spcornelius** [comment]
Yes, I see the wisdom in that. I will modify accordingly.

The principal reason I closed this is because I realized (after several commits) that the drone tests were failing. This was because I had changed PyOdeSys to inherit from OdeSysIterativeBase (for the preconditioning). But that explicitly depends on LAPACK, which I see is now optional in the recent release. As a consequence, the pytests failed in your environments where sundials lacks LAPACK.

I'm now thinking the following course of action would be more prudent, in order to keep LAPACK optional:

1) Continue to have PyOdeSys inherit from OdeSysBase
2) For now, set preconditioning to None by default
3) In a future feature, expose preconditioning to the python front-end (as is done in, e.g. Assimulo).

I will make these changes before another PR.

**Comment by bjodah** [comment]
I think its relying on LAPACK only because I made a full SVD composition the default preconditioner. We could change that to something else which is distributed with AnyODE ( e.g. LU decomposition / blocked LU).

**Comment by spcornelius** [comment]
I may be wrong, but doesn't the LU in anyode also work through BLAS/LAPACK (specifically the function dgetrf_)?

**Comment by bjodah** [comment]
It does, but here's a (re)implementation I've written for another package:

```c++
template <typename Real_t = double>
int getrf(const int nr, const int nc, Real_t * const LUDECOMP_RESTRICT a,
          const int lda, int * const LUDECOMP_RESTRICT ipiv) noexcept {
    // Unblocked algorithm for LU decomposition general matrices
    // employing Doolittle's algorithm with rowswaps.
    //
    // ipiv indexing starts at 1 (Fortran compatibility)
    const int dim = std::min(nr, nc);
    if (dim == 0) return 0;

    int info = 0;
    auto A = [&](int ri, int ci) -> Real_t& { return a[ci*lda + ri]; };
    auto swaprows = [&](int ri1, int ri2) { // this is not cache friendly
        for (int ci=0; ci<dim; ++ci)
            std::swap(A(ri1, ci), A(ri2, ci));
    };

    for (int i=0; i < dim; ++i) {
        int pivrow = i;
        Real_t absmax = std::abs(A(i, i));
        for (int j=i+1; j<nr; ++j) {
            // Find pivot
            Real_t curabs = std::abs(A(j, i));
            if (curabs > absmax){
                absmax = curabs;
                pivrow = j;
            }
        }
        if ((absmax == 0) && (info == 0))
            info = pivrow+1;
        ipiv[i] = pivrow+1;
        if (pivrow != i) {
            // Swap rows
            swaprows(i, pivrow);
        }
        // Eliminate in column
        for (int ri=i+1; ri<nr; ++ri){
            A(ri, i) /= A(i, i);
        }
        // Subtract from rows
        for (int ci=i+1; ci<nc; ++ci){
            const Real_t A_i_ci = A(i, ci);
            for (int ri=i+1; ri<nr; ++ri){
                A(ri, ci) -= A(ri, i)*A_i_ci;
            }
        }
    }
    ipiv[dim-1] = dim;
    return info;
}

template <typename Real_t = double>
int getrs(const int n, const int nrhs,
          Real_t * const LUDECOMP_RESTRICT a, const int lda,
          const int * const LUDECOMP_RESTRICT ipiv,
          Real_t * const LUDECOMP_RESTRICT b, const int ldb){
    if (n < 0) return -1;
    if (n == 0) return 0;
    if (nrhs < 0) return -2;
    if (a == nullptr) return -3;
    if (lda < 0) return -4;
    if (ipiv == nullptr) return -5;
    if (b == nullptr) return -6;
    if (ldb < 0) return -7;
    auto A = [&](const int ri, const int ci) -> Real_t& { return a[ri + ci*lda]; };
    auto B = [&](const int ri, const int idx) -> Real_t& { return b[ri + idx*ldb]; };
    for (int k=0; k<nrhs; ++k){
        for (int i=0; i<n; ++i)
            if (ipiv[i]-1 != i)
                std::swap(B(i, k), B(ipiv[i]-1, k));
        for (int i=1; i<n; ++i){
            for (int j=0; j<i; ++j)
                B(i, k) -= A(i, j)*B(j, k);
        }
        for (int i=n-1; i>=0; --i){
            for (int j=i+1; j<n; ++j)
                B(i, k) -= A(i, j)*B(j, k);
            B(i, k) /= A(i, i);
        }
    }
    return 0;
}
```
(I'm on my phone so pasting it here)

**Comment by spcornelius** [comment]
Impressive, on a phone! 

I'm not sure the best way to proceed; I only recently realized AnyODE is a separate repository! But I guess since my previouse PRs  have already modified the copies included in pycvodes, I can modify them again to include this blas-less implementation. 

I suppose later you (or I) could incorporate these changes into the versions in the anyode repository....

**Comment by bjodah** [comment]
Sounds good. I'm on the road right now so do whatever is easiest for you
and I'll see to it that changes get in the other repository once I'm back.

**Pull request closed without merging**
